### ISSUE TITLE
对部分内容的请教

### ISSUE THREAD

**Issue by nnnpa31** [chenjia404/p2ptunnel#12]
您好，我对这几点有一些疑问，恳请答疑：

`如果两台电脑都是内网，会通过其它节点进行数据中继`
这里的“其它节点”来源是什么？是 libp2p 社区用爱发电搭建的节点吗？还是您提供的节点？

`如果双方节点无法进行直连，会有其它节点进行中继转发`
这是不是意味着在双端皆为内网的情况下最终行为类似 frp 的流量转发，而不是 p2p udp 打洞直连？

这里完全不包括任何信任的问题，只是个人近期了解到 libp2p 这个项目，对其中的行为有一些理解的不透彻的地方。

**Comment by chenjia404** [comment]
这个内网是相对公网来讲的，例如两个家庭用户，都是在nat下面，在不同的路由器下面，无法直接连接。这个地方的表述后续修改一下，不是很准确。
在一定情况下，就可以通过libp2p打洞建立连接，有可能使用一个中继节点进行连接。

**Comment by nnnpa31** [comment]
> 在一定情况下，就可以通过libp2p打洞建立连接，有可能使用一个中继节点进行连接。

所以，在双方网络都隐藏在不同 nat 下时， libp2p 的行为顺序是：直接连接->打洞连接->中继节点流量转发

这样理解对吗？

**Comment by chenjia404** [comment]
是的，中继节点这个不确定，有时候找不到中继节点，不过后续我可能会运行一些中继节点。

**Comment by nnnpa31** [comment]
这里有一个来自官方的、很详细的文章解释这个过程：

https://docs.libp2p.io/concepts/nat/hole-punching/
